# Generated by Django 4.2.11 on 2024-07-06 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0002_bids_comments_alter_user_id_listing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="listing",
            name="created_time",
            field=models.DateField(auto_now_add=True),
        ),
    ]
