# Generated by Django 4.2.11 on 2024-07-06 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0005_comment_comment_alter_listing_details"),
    ]

    operations = [
        migrations.RenameField(
            model_name="listing",
            old_name="price",
            new_name="starting_bid",
        ),
        migrations.RemoveField(
            model_name="listing",
            name="image",
        ),
        migrations.AddField(
            model_name="listing",
            name="category",
            field=models.CharField(default="", max_length=64),
        ),
        migrations.AddField(
            model_name="listing",
            name="image_url",
            field=models.URLField(blank=True),
        ),
    ]
