# Generated by Django 4.2.11 on 2024-07-07 02:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0007_watchlist"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bid",
            name="bidder",
        ),
        migrations.RemoveField(
            model_name="bid",
            name="time",
        ),
        migrations.AddField(
            model_name="bid",
            name="user",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bid",
            name="listing_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bid",
                to="auctions.listing",
            ),
        ),
    ]
