# Generated by Django 4.2.11 on 2024-07-07 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0010_rename_amt_bid_bid_amount"),
    ]

    operations = [
        migrations.RenameField(
            model_name="bid",
            old_name="bid_amount",
            new_name="amt",
        ),
    ]
