# Generated by Django 4.2.11 on 2024-07-07 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auctions", "0011_rename_bid_amount_bid_amt"),
    ]

    operations = [
        migrations.AddField(
            model_name="listing",
            name="closed",
            field=models.BooleanField(default=False),
        ),
    ]
